FROM node:22-alpine

WORKDIR /app

# Optimization: Cache dependencies
COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

# Copy rest of the code
COPY . .

EXPOSE 5173

# Host 0.0.0.0 is required for Docker access
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
